/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as CrossRouteImport } from './routes/cross'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OversoldRouteImport } from './routes/oversold'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as XbaggerRouteImport } from './routes/xbagger'
import { Route as CompanyTickerRouteImport } from './routes/company.$ticker'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossRoute = CrossRouteImport.update({
  id: '/cross',
  path: '/cross',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OversoldRoute = OversoldRouteImport.update({
  id: '/oversold',
  path: '/oversold',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const XbaggerRoute = XbaggerRouteImport.update({
  id: '/xbagger',
  path: '/xbagger',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTickerRoute = CompanyTickerRouteImport.update({
  id: '/company/$ticker',
  path: '/company/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/cross': typeof CrossRoute
  '/discover': typeof DiscoverRoute
  '/evidence': typeof EvidenceRoute
  '/handoff': typeof HandoffRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/oversold': typeof OversoldRoute
  '/quality': typeof QualityRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/universe': typeof UniverseRoute
  '/watchlist': typeof WatchlistRoute
  '/xbagger': typeof XbaggerRoute
  '/company/$ticker': typeof CompanyTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/cross': typeof CrossRoute
  '/discover': typeof DiscoverRoute
  '/evidence': typeof EvidenceRoute
  '/handoff': typeof HandoffRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/oversold': typeof OversoldRoute
  '/quality': typeof QualityRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/universe': typeof UniverseRoute
  '/watchlist': typeof WatchlistRoute
  '/xbagger': typeof XbaggerRoute
  '/company/$ticker': typeof CompanyTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/cross': typeof CrossRoute
  '/discover': typeof DiscoverRoute
  '/evidence': typeof EvidenceRoute
  '/handoff': typeof HandoffRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/oversold': typeof OversoldRoute
  '/quality': typeof QualityRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/universe': typeof UniverseRoute
  '/watchlist': typeof WatchlistRoute
  '/xbagger': typeof XbaggerRoute
  '/company/$ticker': typeof CompanyTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/cross'
    | '/discover'
    | '/evidence'
    | '/handoff'
    | '/history'
    | '/login'
    | '/oversold'
    | '/quality'
    | '/queue'
    | '/settings'
    | '/universe'
    | '/watchlist'
    | '/xbagger'
    | '/company/$ticker'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/cross'
    | '/discover'
    | '/evidence'
    | '/handoff'
    | '/history'
    | '/login'
    | '/oversold'
    | '/quality'
    | '/queue'
    | '/settings'
    | '/universe'
    | '/watchlist'
    | '/xbagger'
    | '/company/$ticker'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/cross'
    | '/discover'
    | '/evidence'
    | '/handoff'
    | '/history'
    | '/login'
    | '/oversold'
    | '/quality'
    | '/queue'
    | '/settings'
    | '/universe'
    | '/watchlist'
    | '/xbagger'
    | '/company/$ticker'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CrossRoute: typeof CrossRoute
  DiscoverRoute: typeof DiscoverRoute
  EvidenceRoute: typeof EvidenceRoute
  HandoffRoute: typeof HandoffRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  OversoldRoute: typeof OversoldRoute
  QualityRoute: typeof QualityRoute
  QueueRoute: typeof QueueRoute
  SettingsRoute: typeof SettingsRoute
  UniverseRoute: typeof UniverseRoute
  WatchlistRoute: typeof WatchlistRoute
  XbaggerRoute: typeof XbaggerRoute
  CompanyTickerRoute: typeof CompanyTickerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross': {
      id: '/cross'
      path: '/cross'
      fullPath: '/cross'
      preLoaderRoute: typeof CrossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversold': {
      id: '/oversold'
      path: '/oversold'
      fullPath: '/oversold'
      preLoaderRoute: typeof OversoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xbagger': {
      id: '/xbagger'
      path: '/xbagger'
      fullPath: '/xbagger'
      preLoaderRoute: typeof XbaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$ticker': {
      id: '/company/$ticker'
      path: '/company/$ticker'
      fullPath: '/company/$ticker'
      preLoaderRoute: typeof CompanyTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  CrossRoute: CrossRoute,
  DiscoverRoute: DiscoverRoute,
  EvidenceRoute: EvidenceRoute,
  HandoffRoute: HandoffRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  OversoldRoute: OversoldRoute,
  QualityRoute: QualityRoute,
  QueueRoute: QueueRoute,
  SettingsRoute: SettingsRoute,
  UniverseRoute: UniverseRoute,
  WatchlistRoute: WatchlistRoute,
  XbaggerRoute: XbaggerRoute,
  CompanyTickerRoute: CompanyTickerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
